server:
  port: 8080
  servlet:
    context-path: /api

spring:
  application:
    name: wallpaper-management
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/wallpaper_management?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true&useSSL=false
    username: root
    password: root
    # 连接池配置
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      connection-timeout: 30000
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB
  main:
    allow-bean-definition-overriding: true
  # Flyway配置  
#  flyway:
#    enabled: true
#    baseline-on-migrate: true
#    locations: classpath:db/migration
#    validate-on-migrate: true
#    out-of-order: true
#    table: flyway_schema_history

mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*.xml
  type-aliases-package: com.wallpaper.management.entity
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      id-type: AUTO
      logic-delete-field: is_deleted
      logic-delete-value: 1
      logic-not-delete-value: 0

# 文件上传路径配置
file:
  upload:
    path: D:/wallpaper/uploads/
    allowed-types: jpg,jpeg,png,gif,webp
    max-size: 10485760  # 10MB
    base-url: http://localhost:8080/api/file/
    thumbnail:
      width: 300
      height: 200

# Shiro配置
shiro:
  web:
    enabled: true
  loginUrl: /login
  successUrl: /index
  unauthorizedUrl: /unauthorized
  sessionManager:
    sessionIdCookieEnabled: true
    sessionIdUrlRewritingEnabled: false

# JWT配置
jwt:
  secret: wallpaper-management-secret-key
  expire: 86400  # 过期时间（秒）- 24小时

# Knife4j配置
knife4j:
  enable: true
  setting:
    language: zh-CN
    enableSwaggerModels: true
    enableDocumentManage: true
    swaggerModelName: 实体类列表
    enableVersion: false
    enableReloadCacheParameter: false
    enableAfterScript: true
    enableFilterMultipartApiMethodType: POST
    enableFilterMultipartApis: false
    enableRequestCache: true
    enableHost: false
    enableHostText: 
    enableDynamicParameter: false
    enableDebug: true
    enableOpenApi: false
    enableGroup: true 